apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chartRef:
    kind: OCIRepository
    name: podinfo
  interval: 1h
  values:
    ingress:
      enabled: true
      hosts:
        - paths:
            - path: /
              pathType: Prefix
